backend:
  name: git-gateway
  branch: main

media_folder: "assets/blog-images"
public_folder: "/assets/blog-images"

collections:
  - name: "blog"
    label: "Blog Posts"
    label_singular: "Blog Post"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Penulis", name: "author", widget: "string", default: "ZAM ZAM" }
      - { label: "Tanggal", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Kategori", name: "categories", widget: "select", multiple: true, options: ["Tips", "Tutorial", "Produktivitas", "Belajar"] }
      - { label: "Tag", name: "tags", widget: "list", default: ["umum"] }
      - { label: "Ringkasan", name: "excerpt", widget: "text" }
      - label: "Isi Konten"
        name: "body"
        widget: "markdown"
        buttons:
          - bold
          - italic
          - code
          - link
          - heading-two
          - heading-three
          - heading-four
          - quote
          - bulleted-list
          - numbered-list
        editor_components:
          - image
          - youtube-embed
      - { label: "Featured Post", name: "featured", widget: "boolean", default: false }
