backend:
  name: git-gateway
  branch: main

media_folder: "assets/blog-images"
public_folder: "/assets/blog-images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Penulis", name: "author", widget: "string", default: "ZAM ZAM" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Kategori", name: "categories", widget: "list", default: ["Tips"] }
      - { label: "Tag", name: "tags", widget: "list" }
      - { label: "Ringkasan", name: "excerpt", widget: "text" }
      - { label: "Isi Konten", name: "body", widget: "markdown", 
          buttons: ["bold", "italic", "link", "heading-two", "heading-three", "heading-four", "quote", "code", "image"],
          editor_components: ["image", "youtube-embed"] }
      - { label: "Featured Post", name: "featured", widget: "boolean", default: false }
      editor:
  preview: false
  widgets:
    markdown:
      buttons:
        - bold
        - italic
        - heading-two
        - heading-three
        - heading-four
        - quote
        - code
        - link
        - image
        - bulleted-list
        - numbered-list
      editorComponents:
        - image
        - youtube-embed
        - code-block
        - custom-html
